### ISSUE TITLE
Publish Facebook events

### ISSUE THREAD

**Issue by curthasselschwert** [zendeskarchive/broadcast#1]
Thanks for this great gem. I think it would be excellent if we could publish events to Facebook as well as posting to a wall. I'd be happy to try contributing some code if you think this is worthwhile.

**Comment by marcinbunsch** [comment]
Interesting idea - do you mean posting a message to a event wall or creating a whole new event?

**Comment by curthasselschwert** [comment]
I meant posting a whole new event. As an example, we have a client that hosts informational events to attract new customers. It would be great to publish the events to their company Facebook page (and then possibly invite all of their followers).

**Comment by curthasselschwert** [comment]
The only tricky thing about doing this would be that Facebook events take a different set of options (start_time, end_time, location, etc.).

**Comment by marcinbunsch** [comment]
Although the idea is tempting, I'm not sure that would work well with the broadcast API for messages. Broadcast works well across all services because it has a common structure that wraps around the concept of the message (which has a body and an optional subject). Introducing events would also introduce complexity and break the simplicity of broadcast's API.

Creating FB events seems like something a FB-specific gem would be great for - we've used koala (https://github.com/arsduo/koala) for broadcast and can recommend it, it's great! Maybe that would be a better fit for your use case?

**Comment by curthasselschwert** [comment]
After thinking about it some more, I would say I have to agree. I was using various different gems to publish to various social networks and publishing events to Facebook made the interface for the class I created fairly clunky. Since events really are entirely different objects, I guess they should be handled on their own.

**Comment by marcinbunsch** [comment]
Thanks for the response, I'll close this issue then. Also, thanks for checking out broadcast! I hope you find it useful even it doesn't support events :)
